
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: crawler-parser
  rabbitmq:
    host: 192.168.112.131
    username: admin
    password: admin